baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "caldito.me"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:slug/"

#[[menu.main]]
#name = "Categories"
#url = "/categories/"
#weight = 1
[[menu.main]]
name = "writing"
url = "/post/"
weight = 1
[[menu.main]]
name = "about"
url = "/about"
weight = 2
[[menu.main]]
name = "resume"
url = "/docs/resume.pdf"
weight = 3
[[menu.feed]]
name = "rss"
url = "/index.xml"
[[menu.feed]]
name = "github"
url = "https://github.com/caldito"

[params]
custom_css = ["css/theme-override.css"]
description = "Caldito's site"
footer = "© 2024 Caldito [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0)"
